version: '3.8'

services:
  api:
    container_name: rocket-bank-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rocket-bank-network
    depends_on:
      - database
    env_file:
      - .env

  database:
    container_name: rocket-bank
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    networks:
      - rocket-bank-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  rocket-bank-network:


volumes:
  pgdata:
