version: '3.8'

services:
  database:
    container_name: rocket-bank
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    networks:
      - rocket-bank-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  rocket-bank-network:


volumes:
  pgdata:
